force-app/main/default/objects/AWS_Configuration__mdt/AWS_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>AWS Configuration</label>
    <pluralLabel>AWS Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/AWS_Configuration__mdt/fields/AWS_Region__c.field-meta.xml
<CustomField>
    <fullName>AWS_Region__c</fullName>
    <label>AWS Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__mdt/fields/AWS_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Secret_Key__c</fullName>
    <label>AWS Secret Key</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__mdt/fields/IAM_Role_ARN__c.field-meta.xml
<CustomField>
    <fullName>IAM_Role_ARN__c</fullName>
    <label>IAM Role ARN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Configuration__mdt/fields/S3_Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>S3_Bucket_Name__c</fullName>
    <label>S3 Bucket Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWSConfig.cls
//class developed for singleton pattern
public class AWSConfig {
    private static AWSConfig awsConfigInstance = NULL;
    private AWS_Configuration__mdt config;
    private AWSConfig(String developerName){
        config = [
            SELECT AWS_Access_Key__c, AWS_Region__c, AWS_Secret_Key__c, S3_Bucket_Name__c, IAM_Role_ARN__c
            FROM AWS_Configuration__mdt WHERE DeveloperName = :developerName
            LIMIT 1
        ];
    }
    public static AWSConfig getAwsConfigInstance(String developerName){
        if(awsConfigInstance == NULL){
            awsConfigInstance = new AWSConfig(developerName);
        }
        return awsConfigInstance;
    }
    public String getAccessKey(){
        return config.AWS_Access_Key__c;
    }
    public String getRegion(){
        return config.AWS_Region__c;
    }
    public String getSecretKey(){
        return config.AWS_Secret_Key__c;
    }
    public String getBucketName(){
        return config.S3_Bucket_Name__c;
    }
}